In [4]:
import numpy as np
import matplotlib.pyplot as plt
import h5py

In [7]:
path_metadata = '/lustre/fsn1/projects/rech/prk/uid35yw/CosmoGrid/CosmoGridV1_metainfo.h5'

In [8]:
meta_info = h5py.File(path_metadata, 'r')

In [18]:
shells = np.load('/lustre/fsn1/projects/rech/prk/uid35yw/'+meta_info['parameters']['fiducial']['path_par'][0].decode('utf-8')+"run_0000/baryonified_shells.npz")["shells"]

In [21]:
shells

array([[  315.        ,   842.        ,   469.        , ...,
          401.        ,   386.        ,   266.        ],
       [  357.        ,   323.        ,   283.        , ...,
         1331.42364547,   754.50722274,  3498.14999295],
       [  603.5854711 ,   461.76422347,   954.45870086, ...,
          557.        ,   723.        ,   635.        ],
       ...,
       [ 8918.        , 10348.        , 10766.        , ...,
        10363.        , 10271.        , 12326.        ],
       [10071.        , 12437.        , 13604.        , ...,
        11031.        , 12615.        , 13559.        ],
       [16421.        , 15540.        , 15326.        , ...,
        18190.        , 15983.        , 14266.        ]])

In [13]:
meta_info['parameters']['fiducial']['path_par'][0]+"run_0000/compressed_shells.npz"

TypeError: can't concat str to numpy.bytes_

In [5]:
meta_info['shell_info']['CosmoGrid']['raw']['fiducial']['cosmo_fiducial']['lower_z']

array([0.        , 0.01277548, 0.02578057, 0.03902289, 0.05251003,
       0.06625001, 0.08025129, 0.09452274, 0.1090737 , 0.1239141 ,
       0.1390541 , 0.1545049 , 0.1702779 , 0.1863854 , 0.2028402 ,
       0.2196561 , 0.2368474 , 0.2544296 , 0.2724188 , 0.2908324 ,
       0.3096887 , 0.3290072 , 0.3488088 , 0.3691156 , 0.3899513 ,
       0.4113412 , 0.4333125 , 0.4558939 , 0.4791168 , 0.5030144 ,
       0.5276226 , 0.5529801 , 0.5791287 , 0.6061132 , 0.6339825 ,
       0.6627892 , 0.6925908 , 0.7234494 , 0.7554329 , 0.7886154 ,
       0.823078  , 0.8589094 , 0.8962073 , 0.9350792 , 0.9756439 ,
       1.018033  , 1.062392  , 1.108884  , 1.157691  , 1.209016  ,
       1.263089  , 1.320168  , 1.380549  , 1.444565  , 1.5126    ,
       1.585096  , 1.662563  , 1.745596  , 1.834892  , 1.931274  ,
       2.03572   , 2.149406  , 2.273754  , 2.410506  , 2.561821  ,
       2.730411  , 2.919731  , 3.134262  , 3.379937  ], dtype=float32)

In [6]:
meta_info['shell_info']['CosmoGrid']['raw']['fiducial']['cosmo_fiducial']['upper_z']

array([0.01277548, 0.02578057, 0.03902289, 0.05251003, 0.06625001,
       0.08025129, 0.09452274, 0.1090737 , 0.1239141 , 0.1390541 ,
       0.1545049 , 0.1702779 , 0.1863854 , 0.2028402 , 0.2196561 ,
       0.2368474 , 0.2544296 , 0.2724188 , 0.2908324 , 0.3096887 ,
       0.3290072 , 0.3488088 , 0.3691156 , 0.3899513 , 0.4113412 ,
       0.4333125 , 0.4558939 , 0.4791168 , 0.5030144 , 0.5276226 ,
       0.5529801 , 0.5791287 , 0.6061132 , 0.6339825 , 0.6627892 ,
       0.6925908 , 0.7234494 , 0.7554329 , 0.7886154 , 0.823078  ,
       0.8589094 , 0.8962073 , 0.9350792 , 0.9756439 , 1.018033  ,
       1.062392  , 1.108884  , 1.157691  , 1.209016  , 1.263089  ,
       1.320168  , 1.380549  , 1.444565  , 1.5126    , 1.585096  ,
       1.662563  , 1.745596  , 1.834892  , 1.931274  , 2.03572   ,
       2.149406  , 2.273754  , 2.410506  , 2.561821  , 2.730411  ,
       2.919731  , 3.134262  , 3.379937  , 3.5       ], dtype=float32)

In [13]:
prior_leakage = np.load('../data_utils/prior_psf_sys_SP_v1.4.5_leak_corr_cosmogrid.npy', allow_pickle=True).item()

In [9]:
prior_leakage['bin1']['cov'] = np.eye(3)*1e-12

In [14]:
prior_leakage

{'bin1': {'mean': array([0.00337221, 1.08836809, 0.04954937]),
  'cov': array([[1.e-12, 0.e+00, 0.e+00],
         [0.e+00, 1.e-12, 0.e+00],
         [0.e+00, 0.e+00, 1.e-12]])}}

In [12]:
np.save("../data_utils/prior_psf_sys_SP_v1.4.5_leak_corr_cosmogrid.npy", prior_leakage)